# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sweep_add <- function(A, alpha) {
    .Call('_hmmfb_sweep_add', PACKAGE = 'hmmfb', A, alpha)
}

sweep_add_logexp <- function(A, alpha) {
    .Call('_hmmfb_sweep_add_logexp', PACKAGE = 'hmmfb', A, alpha)
}

logsumexp <- function(x) {
    .Call('_hmmfb_logsumexp', PACKAGE = 'hmmfb', x)
}

fbiter <- function(A, alpha, B) {
    .Call('_hmmfb_efbiter', PACKAGE = 'hmmfb', A, alpha, B)
}

cpp_cumsum <- function(x) {
    .Call('_hmmfb_cpp_cumsum', PACKAGE = 'hmmfb', x)
}

gen_bt <- function(linit, lA, B, ntimes) {
    .Call('_hmmfb_gen_bt', PACKAGE = 'hmmfb', linit, lA, B, ntimes)
}

forward_rcpp <- function(linit, lA, B, ntimes, return_all = FALSE) {
    .Call('_hmmfb_forward_rcpp', PACKAGE = 'hmmfb', linit, lA, B, ntimes, return_all)
}

